<a href="https://colab.research.google.com/github/ConstanzaG/Proyecto-Final-Grupo4-Turismo/blob/main/creacion_turismo_db.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Librerías necesarias para cargar dataframes a .db
import pandas as pd
import sqlite3

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (25) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
turismo = pd.read_csv('BBDD 4X30.csv', sep=';')
turismo.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (25) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Código Comuna origen,Comuna de origen,Código Provincia origen,Provincia Origen,Código Región origen,Región de origen,Código Comuna destino,Comuna de destino,Destino turístico,Código Provincia Destino,...,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,4302,Combarbalá,43,Limarí,4,Coquimbo,6110,Mostazal,Resto región Libertador General Bernardo O'Hig...,61,...,"0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","14,0453348159790000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000"
1,9108,Lautaro,91,Cautín,9,La Araucanía,6103,Coinco,Resto región Libertador General Bernardo O'Hig...,61,...,"0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000"
2,3201,Chañaral,32,Chañaral,3,Atacama,13102,Cerrillos,Resto región Metropolitana de Santiago,131,...,"5,4610056877136200","2,7688646316528300","11,5984811782836000","0,0000000000000000","0,0000000000000000","3,4468264579772900","0,0000000000000000","6,4007334709167400","0,0000000000000000","0,0000000000000000"
3,4303,Monte Patria,43,Limarí,4,Coquimbo,13105,El Bosque,Resto región Metropolitana de Santiago,131,...,"19,7908353805541000","0,0000000000000000","4,0848832130432100","4,1758556365966700","0,0000000000000000","7,7732558250427200","0,0000000000000000","3,7519521713256800","0,0000000000000000","0,0000000000000000"
4,13604,Padre Hurtado,136,Talagante,13,Metropolitana de Santiago,9110,Melipeuco,Araucanía Andina,91,...,"6,1069808006286600","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","21,3769102096557000","12,6999535560607000","0,0000000000000000","0,0000000000000000"

In [ ]:
turismo.columns

Index(['Código Comuna origen', 'Comuna de origen', 'Código Provincia origen',
       'Provincia Origen', 'Código Región origen', 'Región de origen',
       'Código Comuna destino', 'Comuna de destino', 'Destino turístico ',
       'Código Provincia Destino', 'Provincia de destino',
       'Código Región destino', 'Región de destino', 'Años', 'Enero',
       'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto',
       'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
      dtype='object')

In [ ]:
#Creamos archivo .db en el directorio del programa
connection = sqlite3.connect('turismo.db') 
c = connection.cursor()
#Creamos la tabla donde se cargará el dataframe
c.execute('CREATE TABLE IF NOT EXISTS TURISMO_RECEPTIVO(Código_Comuna_origen text, Comuna_origen text, Código_Provincia_origen text, Provincia_Origen text, Código_Región_origen text, Región_origen text, Código_Comuna_destino text,' +
                                                'Comuna_destino text, Destino_turístico text, Código_Provincia_Destino text, Provincia_destino text, Código_Región_destino text, Región_destino text,' + 
                                                'Años number, Enero number, Febrero number,	Marzo number, Abril number, Mayo number, Junio number, Julio number, Agosto number, Septiembre number, Octubre number,' +
                                                'Noviembre number, Diciembre number)')
connection.commit()
#Ejemplo de dataframe creado en pandas en base a una colección del tipo diccionario
data = {'Código_Comuna_origen': turismo['Código Comuna origen'],
        'Comuna_origen': turismo['Comuna de origen'],
        'Código_Provincia_origen': turismo['Código Provincia origen'],
        'Provincia_Origen': turismo['Provincia Origen'],
        'Código_Región_origen': turismo['Código Región origen'],
        'Región_origen': turismo['Región de origen'],
        'Código_Comuna_destino': turismo['Código Comuna destino'],
        'Comuna_destino': turismo['Comuna de destino'],
        'Destino_turístico': turismo['Destino turístico '],
        'Código_Provincia_Destino': turismo['Código Provincia Destino'],
        'Provincia_destino': turismo['Provincia de destino'],
        'Código_Región_destino': turismo['Código Región destino'],
        'Región_destino': turismo['Región de destino'],
        'Años': turismo['Años'],
        'Enero': turismo['Enero'],
        'Febrero': turismo['Febrero'],
        'Marzo': turismo['Marzo'],
        'Abril': turismo['Abril'],
        'Mayo': turismo['Mayo'],
        'Junio': turismo['Junio'],
        'Julio': turismo['Julio'],
        'Agosto': turismo['Agosto'],
        'Septiembre': turismo['Septiembre'],
        'Octubre': turismo['Octubre'],
        'Noviembre': turismo['Noviembre'],
        'Diciembre': turismo['Diciembre'],

}
df = pd.DataFrame(data, columns= ['Código_Comuna_origen', 'Comuna_origen', 'Código_Provincia_origen', 'Provincia_Origen', 'Código_Región_origen', 'Región_origen', 'Código_Comuna_destino', 'Comuna_destino',
                                  'Destino_turístico', 'Código_Provincia_Destino', 'Provincia_destino', 'Código_Región_destino', 'Región_destino', 'Años', 'Enero', 'Febrero',	'Marzo', 'Abril', 'Mayo',
                                  'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])

df.to_sql('TURISMO_RECEPTIVO', connection, if_exists='replace', index = False)
#Consultamos la tabla creada en la base de datos .db para ver que proceso fue exitoso
df = pd.read_sql('SELECT * FROM TURISMO_RECEPTIVO', connection)
df

,Código_Comuna_origen,Comuna_origen,Código_Provincia_origen,Provincia_Origen,Código_Región_origen,Región_origen,Código_Comuna_destino,Comuna_destino,Destino_turístico,Código_Provincia_Destino,...,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,4302,Combarbalá,43,Limarí,4,Coquimbo,6110,Mostazal,Resto región Libertador General Bernardo O'Hig...,61,...,"0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","14,0453348159790000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000"
1,9108,Lautaro,91,Cautín,9,La Araucanía,6103,Coinco,Resto región Libertador General Bernardo O'Hig...,61,...,"0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000"
2,3201,Chañaral,32,Chañaral,3,Atacama,13102,Cerrillos,Resto región Metropolitana de Santiago,131,...,"5,4610056877136200","2,7688646316528300","11,5984811782836000","0,0000000000000000","0,0000000000000000","3,4468264579772900","0,0000000000000000","6,4007334709167400","0,0000000000000000","0,0000000000000000"
3,4303,Monte Patria,43,Limarí,4,Coquimbo,13105,El Bosque,Resto región Metropolitana de Santiago,131,...,"19,7908353805541000","0,0000000000000000","4,0848832130432100","4,1758556365966700","0,0000000000000000","7,7732558250427200","0,0000000000000000","3,7519521713256800","0,0000000000000000","0,0000000000000000"
4,13604,Padre Hurtado,136,Talagante,13,Metropolitana de Santiago,9110,Melipeuco,Araucanía Andina,91,...,"6,1069808006286600","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","0,0000000000000000","21,3769102096557000","12,6999535560607000","0,0000000000000000","0,0000000000000000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302536,13110,La Florida,131,Santiago,13,Metropolitana de Santiago,5602,Algarrobo,Litoral Algarrobo - Santo Domingo,56,...,"1.864,6610107421800000","235,9473602771750000","854,4113118648520000","2.320,4689018726300000","9.443,8269052505400000","4.569,2548131942700000","5.886,0006761550900000","5.562,7538251876800000","3.703,1579208374000000",None
302537,15101,Arica,151,Arica,15,Arica y Parinacota,1401,Pozo Almonte,Mamiña,14,...,"993,8193168640130000","669,7946724891660000","940,1384811401360000","1.461,8754844665500000","2.347,7431793212800000","1.692,5453233718800000","1.720,7427177429100000","1.867,3219728469800000","1.755,8371067047100000",None
302538,13123,Providencia,131,Santiago,13,Metropolitana de Santiago,5109,Viña del Mar,Litoral Viña del Mar - Concón,51,...,"1.345,3530235290500000","348,9461660385130000","1.894,0000319480800000","2.579,7193737030000000","7.181,6258645057600000","4.485,9174804687500000","5.472,8340029716400000","4.939,0074748992900000","3.893,6489188671100000",None
302539,5109,Viña del Mar,51,Valparaíso,5,Valparaíso,13114,Las Condes,Santiago Urbano,131,...,"3.350,3738710880200000","8.817,5671491622900000","12.658,0033600330000000","2.991,5966014862000000","6.086,7307806015000000","6.310,0226728916100000","6.006,5390563011100000","7.083,3656225204400000","6.351,5426330566400000",None
302540,13114,Las Condes,131,Santiago,13,Metropolitana de Santiago,5606,Santo Domingo,Litoral Algarrobo - Santo Domingo,56,...,"1.139,5370922088600000","174,0709605216970000","1.224,1530761718700000","2.211,5657272338800000","7.053,5699634552000000","2.608,6066746711700000","4.847,1410565376200000","3.562,5843212604500000","1.825,5556669235200000",None

In [ ]:
df.shape

(302541, 26)

In [ ]:
turismo.shape

(302541, 26)